travis:
  secure:
    BINSTAR_TOKEN: fd9uv+PYrfeK2JEQ1oHIW4s+mhqOjLb4aBRJ6RDPmetRx98u74cqcxHqxVZSLPh2mAROvblFKoASDXExYKs0kIGzU09C0XmmknPkNJdsJ6z9wRpqMfEWqUT7fZbPmrABIGaOacmwVGIRR/sBW1LFk0YSikolvQYzksUwsC/VpwkT3puJA2+CHA9zzY2oHdp0O+myCrtNXuJa9huan+jScd8Q7rOeeB/YG7VB+DwclxD8a/JKcB5L0TseBI6Ivp7EFrfu8VeyeZl/Kc+GXyBom+aljzXs5xAK+nt3vV66vbzWicfVnRUTNF/ieJcYByZOa6LR6XZZWG70STcHMoYlHuqQT1JyFdASBvJ/RVDpE3LHNK3gYDarvVDJGFSPz1Tw2hk3KhtTvk71saKsDgt9sZL7SfUvvj9lr5+1pZJao6IL6ihr+J2H0m1Zt794nyu7l3rJvhXDLaFANYrKoRnDIGlO9sw9mbh/1psMPj3OoQVk+9d6TflCTWWis1MU/wrV6JSxBy3xtrJbyH7/zgrJyAFKzEPaUviRc+iQBAmxJvFNRXjt8MAT0dSNaDC/JCxYe62foO+kwHLD4iP4ZwZgs8wUVMwMTHX20bMbNvyUpoHurTnNH+IruyIHMg3/0rPN6DE/y6blXIQe651vCYtFISi4nToyl8vA8LXRy25Abw8=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
